/*Given 3 strings s1, s2, s3, construct a 4th string 
with appropriate size that will be generated by replacing 
all occurrences of substring s2 by the substring s3 
in the string s1. Also report how many times the 
replacement occurred. No library functions should be used.*/

#include <stdio.h>

//implementing the functions to use first
int mystrlen(char s[]);

int main (void)
{
    char s1[] = "I scream, you scream, we all scream for ice cream!";
    char s2[] = "scream";
    char s3[] = "shout";

    int len1 = mystrlen(s1);
    int len2 = mystrlen(s2);
    int len3 = mystrlen(s3);

    //new string with replaced characters
    char s4[100];
    int len4 = 0;
    for (int i = 0; i < len1; i++) {
        int j;
        for (j = 0; j < len2; j++) {
            if (s1[i+j] != s2[j])
                break;
        }
        if (j == len2) {
            //found;
            for (int k = 0; k < len3; k++) {
                s4[len4++] = s3[k];
            }
            i += j-1;
        }
        else {
            s4[len4++] = s1[i];
        }
    }
    s4[len4] = '\0';
    puts(s4);

    return 0;
}

int mystrlen(char s[]) {
    int i = 0; 
    while (s[i]) i++;
    return i;
}